"""empty message

Revision ID: 311a32c590e5
Revises: 03cc33213c66
Create Date: 2023-11-08 17:45:40.759767

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '311a32c590e5'
down_revision = '03cc33213c66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
        sa.Column('id', sa.INTEGER(), nullable=False),
        sa.Column('name', sa.VARCHAR(length=128), nullable=False),
        sa.Column('birthdate', sa.VARCHAR(length=128), nullable=False),
        sa.Column('username', sa.VARCHAR(length=128), nullable=False),
        sa.Column('password', sa.VARCHAR(length=128), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
