"""plus

Revision ID: 80ff08136610
Revises: 28e81cf632c1
Create Date: 2023-11-09 20:41:45.511178

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80ff08136610'
down_revision = '28e81cf632c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.drop_column('model_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.add_column(sa.Column('model_name', sa.VARCHAR(length=128), nullable=False))

    # ### end Alembic commands ###
